- name: Install Casks from Homebrew
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
  - alfred
  - evernote
  - grammarly
  - jetbrains-toolbox
  - kitty
  - loopback
  - screenflow
  - shadow-beta
  - shiftit
  - signal-beta
  - skype
  - slack-beta
  - steam
  - telegram
  - tidal
  - visual-studio-code
  - vlc

- name: Install applications from Mas
  community.general.mas:
    id: '{{ item }}'
  loop:
  - 409183694           # Keynote
  - 1464122853           # NextDNS
- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.config/kitty/kitty.conf'
    src: '{{ inventory_dir }}/roles/tools_ui/files/kitty.conf'
  - dest: '{{ ansible_env.HOME }}/.config/kitty/color.conf'
    src: '{{ inventory_dir }}/roles/tools_ui/files/color.conf'
  - dest: '{{ ansible_env.HOME }}/.config/kitty/session.conf'
    src: '{{ inventory_dir }}/roles/tools_ui/files/session.conf'
  - src: '{{ inventory_dir }}/roles/tools_ui/files/kitty.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/kitty.fish'

- name: Is touch id sudo enabled
  lineinfile:
    path: /etc/pam.d/sudo
    state: absent
    search_string: auth       sufficient     pam_tid.so
    line: auth       sufficient     pam_tid.so
  check_mode: yes
  changed_when: false
  register: touch_id_sudo


- name: Insert the touch id into the sudo file
  lineinfile:
    path: /etc/pam.d/sudo
    state: present
    insertafter: '^# sudo: auth account password session$'
    search_string: auth       sufficient     pam_tid.so
    line: auth       sufficient     pam_tid.so
  become: yes
  when: not touch_id_sudo.found
