tap "cloudfoundry/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

## programming
# Java
cask "java"
cask "java8"
brew "maven"

# Go
tap "alecthomas/homebrew-tap"
brew "gometalinter"
brew "go"
brew "dep"

# Node JS
brew "node"

# Ruby
brew "ruby"
tap "homebrew/bundle"

# Rust
brew "rustup-init"

# Python
brew "pyenv"

# Ruby
brew "rbenv"

# Php
brew "php"

# Bash
brew "bash"
brew "shellcheck"
brew "yq"
brew "jq"
brew "yamllint"

# VCS
brew "git"
brew "hub"
brew "git-crypt"

tap "git-duet/tap"
brew "git-duet"

brew "mercurial"

# UML
brew "plantuml"

# Formatter
brew "prettier"


cask "jetbrains-toolbox"

## ops
# K8S
brew "kubernetes-helm"
brew "kubectl"
brew "skaffold"
cask "minikube"
cask "google-cloud-sdk"
# HTTP
brew "httpie"
brew "wget"
brew "curl"
# citrix
cask "citrix-workspace"
# aws
brew "awscli"
brew "s3cmd"
# Terraform
brew "terraform"
# Travis
brew "travis"
# CF
brew "cloudfoundry/tap/bosh-cli"
brew "cloudfoundry/tap/bbl"
brew "cloudfoundry/tap/cf-cli"
# Docker
cask "docker"
# virtual box
cask "virtualbox"
# Selenium
cask "chromedriver"
# concourse
cask "fly"

# hugo
brew "hugo"
brew "mkdocs"

# gdb
brew "gdb"

# Enhancements
tap "homebrew/command-not-found"
brew "fasd"
brew "coreutils"
brew "pidof"
brew "tree"
brew "watch"
brew "fswatch"
brew "pstree"
brew "less"

# DNS
brew "bind"

# searchers
brew "grep"
brew "ripgrep"
brew "the_silver_searcher"
cask "alfred"

# gnupg
brew "pinentry-mac"
brew "gnupg"

# passwords
brew "pwgen"
cask "1password"
cask "1password-cli"

# help
brew "tldr"
brew "translate-shell"
# zsh
brew "zsh"
brew "zsh-completions"

# fonts
cask "font-fira-code"

# browsers
cask "firefox-nightly"
cask "google-chrome"

# editors
cask "atom-beta"
cask "skitch"
cask "grammarly"
brew "imagemagick"

# chat
cask "keybase"
cask "skype"
cask "slack-beta"
cask "zoomus"

# dropbox
cask "dropbox"

# games
cask "steam"
