- name: Install packages from Homebrew
  community.general.homebrew:
    state: latest
    name:
    - rustup-init
- name: Link configuration and directories
  file:
    src: '{{ inventory_dir }}/cargo/config'
    dest: '{{ ansible_env.HOME }}/.cargo/config'
    state: link

- name: Init Rust
  shell:
    cmd: rustup-init -y
- name: Update Rust
  shell:
    cmd: rustup update
