#!/usr/bin/env bash

set -euo pipefail

MSG="$1"

check_for_duplicate() {
    test "" = "$(grep "^$2: " "$1" |
        sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
        (>&2 cat "$1")
        (>&2 echo)
        (>&2 echo "Your commit not have the same name duplicated in the $2 field")
        
        exit 1
    }
}

check_for_duplicate "$MSG" Signed-off-by 
check_for_duplicate "$MSG" Co-authored-by
