#!/usr/bin/env bash

set -euo pipefail

STDIN=$(cat /dev/stdin)

if ! echo "$STDIN" | git duet-prepare-commit-msg "$@"; then
	exit $?
fi

exec </dev/tty
if ! npx git-cz --hook; then
	exit $?
fi
exec <&-
