#!/usr/bin/env bash

set -euo pipefail

if ! limactl list | grep --fixed-strings "nerdctl" | grep --fixed-strings --quiet "Running"; then
  limactl start nerdctl
fi

echo exec limactl shell nerdctl -- nerdctl compose "$@"
