- name: Install fish from Homebrew
  community.general.homebrew:
    
    name: '{{ item }}'
  loop:
  - fish
- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.config/fish/config.fish'
    src: '{{ inventory_dir }}/roles/dev_fish/files/config.fish'
  - dest: '{{ ansible_env.HOME }}/.config/fish/fish_plugins'
    src: '{{ inventory_dir }}/roles/dev_fish/files/fishfile'
- name: Set the default shell to fish
  ansible.builtin.user:
    name: '{{ ansible_env.USER }}'
    shell: /usr/local/bin/fish
- name: Update fisher
  shell:
    cmd: fish -c "fisher update"
