- name: Install packages from Homebrew
  community.general.homebrew:
    name:
    - pinentry-mac
    - gnupg
- name: Link configuration and directories
  file:
    src: '{{ inventory_dir }}/gnupg/gpg-agent.conf'
    dest: '{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf'
    state: link
    mode: '600'
- name: Link configuration and directories
  file:
    path: '{{ ansible_env.HOME }}/.gnupg'
    mode: '700'


