- name: Install packages from Homebrew
  community.general.homebrew:
    name: '{{ item }}'
  loop:
  - [bash, bash-completion, bats, shellcheck, shfmt, hyperfine, specdown/repo/specdown]
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
  loop:
  - '{{ ansible_env.HOME }}/.config'
- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.bashrc'
    src: '{{ inventory_dir }}/roles/dev_bash/files/xdg-shim'
  - dest: '{{ ansible_env.HOME }}/.config/bash/bashrc'
    src: '{{ inventory_dir }}/roles/dev_bash/files/bashrc'
