- name: Tap Homebrew repositories
  community.general.homebrew_tap:
    name:
    - PurpleBooth/repo
- name: Install packages from Homebrew
  community.general.homebrew:
    state: latest
    name:
    - PurpleBooth/repo/git-mit
    - git
    - git-crypt
    - git-delta
    - git-lfs
- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.config/git/config'
    src: '{{ inventory_dir }}/git/config'
  - dest: '{{ ansible_env.HOME }}/.config/git/config.insteadofhttp'
    src: '{{ inventory_dir }}/git/config.insteadofhttp'
  - dest: '{{ ansible_env.HOME }}/.config/git/message'
    src: '{{ inventory_dir }}/git/message'
  - dest: '{{ ansible_env.HOME }}/.config/git/ignore'
    src: '{{ inventory_dir }}/git/ignore'
  - dest: '{{ ansible_env.HOME }}/.config/git/init-template/hooks/prepare-commit-msg'
    src: /usr/local/bin/mit-prepare-commit-msg
  - dest: '{{ ansible_env.HOME }}/.config/git/init-template/hooks/commit-msg'
    src: /usr/local/bin/mit-commit-msg
  - dest: '{{ ansible_env.HOME }}/.config/git/init-template/hooks/pre-commit'
    src: /usr/local/bin/mit-pre-commit
  - dest: '{{ ansible_env.HOME }}/.config/git-mit/authors.yml'
    src: '{{ inventory_dir }}/git-mit/authors.yml'
