- name: Check that the Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew
- name: Installing Homebrew
  shell:
    cmd: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: 1
  when: not homebrew.stat.exists
  become: yes
- name: Tap Homebrew repositories
  community.general.homebrew_tap:
    name:
    - PurpleBooth/repo
    - alecthomas/homebrew-tap
    - aws/tap
    - azure/functions
    - cloudfoundry/tap
    - denisidoro/tools
    - hashicorp/tap
    - homebrew/autoupdate
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-versions
    - homebrew/command-not-found
    - homebrew/core
    - snyk/tap
    - specdown/repo
- name: Install Homebrew dependencies
  community.general.homebrew:
    name:
    - mas
    - svn
    state: latest
- name: Install Casks from Homebrew
  community.general.homebrew_cask:
    name:
    - adoptopenjdk8
    - alfred
    - audio-hijack
    - chromedriver
    - dotnet-sdk
    - element
    - evernote
    - firefox-beta
    - fly
    - google-chrome
    - google-cloud-sdk
    - grammarly
    - jetbrains-toolbox
    - loopback
    - mactex-no-gui
    - screenflow
    - shadow-beta
    - shiftit
    - signal-beta
    - skype
    - slack-beta
    - steam
    - telegram
    - tidal
    - visual-studio-code
    - vlc
    - zoom
    state: latest
- name: Install applications from Mas
  community.general.mas:
    id:
    - 409183694
    - 1464122853
    - 1176895641
    state: latest
- name: Install packages from Homebrew
  community.general.homebrew:
    state: latest
    name:
    - PurpleBooth/repo/ed-system-search
    - PurpleBooth/repo/fix-compaudit
    - PurpleBooth/repo/fix-gnupg-permissions
    - PurpleBooth/repo/game-of-life
    - PurpleBooth/repo/gfmfmt
    - PurpleBooth/repo/git-moves-together
    - PurpleBooth/repo/goodreads-quotes
    - PurpleBooth/repo/readable-name-generator
    - PurpleBooth/repo/whatismyip
    - act
    - angular-cli
    - aws-google-auth
    - aws-iam-authenticator
    - awscli
    - azure-cli
    - azure-functions-core-tools
    - bat
    - bats
    - bind
    - coreutils
    - curl
    - dasel
    - direnv
    - dog
    - dust
    - exa
    - fasd
    - fd
    - fdupes
    - ffmpeg
    - findutils
    - firebase-cli
    - fortune
    - fswatch
    - fzf
    - fzy
    - gettext
    - gcc
    - gdb
    - gh
    - gnu-sed
    - go
    - gradle
    - grep
    - hashicorp/tap/waypoint
    - helm
    - httpie
    - hyperfine
    - imagemagick
    - jq
    - kotlin
    - less
    - librsvg
    - lima
    - magic-wormhole
    - mdcat
    - node
    - nushell
    - openjdk
    - pandoc
    - php
    - phpmd
    - pidof
    - prettier
    - procs
    - progress
    - pstree
    - pwgen
    - pyenv
    - python
    - rbenv
    - reattach-to-user-namespace
    - ripgrep
    - rsync
    - ruby
    - s3cmd
    - serverless
    - shellcheck
    - shfmt
    - sk
    - snyk
    - specdown/repo/specdown
    - svn
    - terminal-notifier
    - terraform
    - terragrunt
    - tfsec
    - thefuck
    - translate-shell
    - tree
    - watch
    - wget
    - yamllint
    - yarn
    - yq
    - zoxide
- name: Link packages from Homebrew
  community.general.homebrew:
    state: linked
    name:
    - gettext
- name: Update Homebrew and other Homebrew packages
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
