- name: Install packages from Homebrew
  community.general.homebrew:
    
    name:
    - rustup-init
    - hyperfine

- name: Link configuration and directories
  file:
    path: '{{ ansible_env.HOME }}/.cargo'
    state: directory
    recurse: true

- name: Link configuration and directories
  file:
    src: '{{ inventory_dir }}/roles/dev_rust/files/config'
    dest: '{{ ansible_env.HOME }}/.cargo/config'
    state: link

- name: Init Rust
  shell:
    cmd: rustup-init -y
- name: Update Rust
  shell:
    cmd: rustup update
