- name: Install google-cloud-sdk Cask from Homebrew
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
  - google-cloud-sdk
- name: Update Gcloud
  command:
    cmd: gcloud components update --quiet
- name: Link fish config
  file:
    src: '{{ inventory_dir }}/roles/platform_google_cloud/files/gcloud.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/gcloud.fish'
    state: link
