#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME="$(basename "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"
DUET_HOME="$(brew --prefix)/bin"

EXEC_COMMAND=(
  'GIT_DUET_AUTHORS_FILE="{}"'
  "$DUET_HOME/$SCRIPT_NAME"
  "$@"
)

exec sops exec-file \
  "$HOME/.config/git-duet/authors.yml" \
  "${EXEC_COMMAND[*]}"
