- name: Update Homebrew and other Homebrew packages
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Upgrade all casks
  community.general.homebrew_cask:
    upgrade_all: true
    greedy: true

- name: Upgrade all installed Mac App Store apps
  community.general.mas:
      upgrade_all: yes
