- name: Check that the Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew
- name: Installing Homebrew
  shell:
    cmd: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: 1
  when: not homebrew.stat.exists
  become: yes

- name: Install Homebrew dependencies
  community.general.homebrew:
    name: '{{ item }}'
    
  loop:
  - mas
  - svn
