- name: Install Casks from Homebrew
  community.general.homebrew:
    state: latest
    name:
    - homebrew/cask-fonts/font-fira-code
    - homebrew/cask-fonts/font-fira-code-nerd-font
    - homebrew/cask-fonts/font-iosevka
    - homebrew/cask-fonts/font-iosevka-aile
    - homebrew/cask-fonts/font-iosevka-curly
    - homebrew/cask-fonts/font-iosevka-curly-slab
    - homebrew/cask-fonts/font-iosevka-etoile
    - homebrew/cask-fonts/font-iosevka-nerd-font
    - homebrew/cask-fonts/font-iosevka-slab
    - homebrew/cask-fonts/font-jetbrains-mono
    - homebrew/cask-fonts/font-jetbrains-mono-nerd-font
    - homebrew/cask-fonts/font-libre-baskerville
    - homebrew/cask-fonts/font-mate
    - homebrew/cask-fonts/font-poppins
    - homebrew/cask-fonts/font-source-sans-pro
