- name: Install nvim from Homebrew
  community.general.homebrew:
    state: latest
    name: nvim
- name: Install bottle python package
  pip:
    name: pynvim
    state: latest

- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
    src: '{{ inventory_dir }}/nvim/init.vim'

- name: Create nvim autoload directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
  loop:
  - '{{ ansible_env.HOME }}/.config/nvim/autoload'
  - '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload'

- name: Download plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'

- name: Download plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim'

