- name: Install packages from Homebrew
  community.general.homebrew:
    name: '{{ item }}'
  loop:
  - nvim


- name: Git checkout
  ansible.builtin.git:
      repo: https://github.com/lvim-tech/lvim.git
      dest: '{{ ansible_env.HOME }}/.config/nvim'

- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - src: '{{ inventory_dir }}/roles/dev_vim/files/cfg_nvim.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/nvim.fish'
  - src: '{{ inventory_dir }}/roles/dev_vim/files/vim.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/functions/vim.fish'

