- name: Install packages from Homebrew
  community.general.homebrew:
    name: '{{ item }}'
  loop:
  - nvim

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
  loop:
  - '{{ ansible_env.HOME }}/.config/nvim/autoload'
- name: Download file and force basic auth
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim'

- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - src: '{{ inventory_dir }}/roles/dev_vim/files/cfg_nvim.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/nvim.fish'
  - src: '{{ inventory_dir }}/roles/dev_vim/files/vim.fish'
    dest: '{{ ansible_env.HOME }}/.config/fish/functions/vim.fish'
  - src: '{{ inventory_dir }}/roles/dev_vim/files/init.vim'
    dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
