- name: Install Casks from Homebrew
  community.general.homebrew_cask:
    name:
    - 1password
    - 1password-cli
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
  loop:
  - '{{ ansible_env.HOME }}/.bin'
- name: Link configuration and directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
  - dest: '{{ ansible_env.HOME }}/.bin/1password'
    src: '{{ inventory_dir }}/1password/bin/1password'

- name: Read and set environment variables from 1password without password
  shell:
    cmd: '{{ inventory_dir }}/1password/bin/generate-envsecret'
    args:
      stdin: '{{ vault_password }}'
